### ISSUE TITLE
 Error: No files found

### ISSUE THREAD

**Issue by BakytzhanAkzhol** [ahwayakchih/crx3#4]
**Node**.js version: `11.6.0`
**OS**: `Windows 10 x64`
**Google Chrome version** : `77.0.3865.90(64-bit)`
**Type**: Chrome Application
**CRX3 version**: ``1.1.0``

Hello, everyone.  I have problem with command. It's always crash. What's wrong?
```
crx3 pack -o ../app.crx -p ../key.pem application_name
```
Error logs:
```
Error: No files found
    at writeCRX3File (C:\Users\Bako\AppData\Roaming\nvm\v11.6.0\node_modules\crx3\lib\writeCRX3File.js:61:25)
    at Object.<anonymous> (C:\Users\Bako\AppData\Roaming\nvm\v11.6.0\node_modules\crx3\bin\crx3.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
```

Directory structures:
```
myapp/
├── dist/ <-- run command in here
       ├── static/
       ├── build/
       └── manifest.json
├── src/
├── app.crx
└── key.pem

```

manifest.json
```application:json
{
  "manifest_version": 2,
  "version": "0.6.166",
  "minimum_chrome_version": "40",
  "name": "application_name",
  "short_name": "....",
  "icons": {
    "48": "...",
    "96": "...",
    "192": "..."
  },
  "key": "....",
  "update_url": "...",
  "offline_enabled": true,
  "permissions": [],
  "app": {
    "background": {
      "scripts": [
        "static/background.js"
      ]
    }
  }
}
```

**Comment by BakytzhanAkzhol** [comment]
## Update question

I wrote this script for auto-build: 
```javascript
#!/usr/bin/env node

const crx3 = require('crx3');

crx3(['./app/manifest.json'], {
    keyPath: './app.pem',
    crxPath: '../app.crx',
    zipPath: '../app.zip'
})
    .then(() => console.log('done'))
    .catch(console.error)
;
```
## First problem: 

Error log:
```
 - node  release.js[9472]: src\node_crypto.cc:2973: Assertion `args[*offset]->IsInt32()' failed.
 1: 00007FF61D503FDA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4714
 2: 00007FF61D4A8AD6 uv_loop_fork+80918
 3: 00007FF61D4A8B8F uv_loop_fork+81103
 4: 00007FF61D3C4349 std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >+9336
9
 5: 00007FF61D3C476D std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >+9442
9
 6: 00007FF61D3C69B9 std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >+1032
09
 7: 00007FF61D9120BE v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+59870
 8: 00007FF61D913620 v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+65344
 9: 00007FF61D9125B9 v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+61145
10: 00007FF61D91249B v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+60859
11: 0000002341150361

```
CRX file not generated. Its file size is 0 bytes

## Second problem. When I try use my .pem file key, then shows error:
Error log: 
```
               this.crx.appId = createCrxId(this.crx.keys.publicKey);
                                                           ^

TypeError: Cannot read property 'publicKey' of null
    at CRX3Stream.crxInit (C:\project\node_modules\crx3\lib\crx3stream.js:127:46)
    at CRX3Stream._write (C:\project\node_modules\crx3\lib\crx3stream.js:86:9)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at CRX3Stream.Writable.write (_stream_writable.js:299:11)
    at PassThrough.ondata (_stream_readable.js:693:20)
    at PassThrough.emit (events.js:193:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at PassThrough.Readable.push (_stream_readable.js:224:10)
```

**Comment by ahwayakchih** [comment]
@BakytzhanAkzhol in your first example, have you tried running it like this:

```
crx3 pack -o ../app.crx -p ../key.pem ../src
```

As for using API, can you clone this repository, and run the following:

```
cd crx3
npm install
node example/example.js
```
What i mean is, can you try if the example code works, when called from the project's directory.

**Comment by BakytzhanAkzhol** [comment]
Hi, thank you for answer. 

I run command on the command line:
```crx3 pack -o ../app.crx -p ../key.pem ./manifest.json```

The result was an error:
```
"C:\projects\chromeApp\key.pem" already exists but could not be loaded.
C:\Users\CHOSENONE\AppData\Roaming\nvm\v11.6.0\node_modules\crx3\lib\crx3stream.js:127
                this.crx.appId = createCrxId(this.crx.keys.publicKey);
                                                           ^

TypeError: Cannot read property 'publicKey' of null
    at CRX3Stream.crxInit (C:\Users\CHOSENONE\AppData\Roaming\nvm\v11.6.0\node_modules\crx3\lib\crx3stream.js:127:46)
    at CRX3Stream._write (C:\Users\CHOSENONE\AppData\Roaming\nvm\v11.6.0\node_modules\crx3\lib\crx3stream.js:86:9)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at CRX3Stream.Writable.write (_stream_writable.js:299:11)
    at PassThrough.ondata (_stream_readable.js:693:20)
    at PassThrough.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at PassThrough.Readable.push (_stream_readable.js:224:10)
```

Second, 
I cloned the project and executed the code as you said. The result was an error:
``` node example/example.js ```
Error logs:
```
"C:\project\temp\example\example-extension.pem" already exists but could not be loaded.
C:\project\temp\lib\crx3stream.js:127
                this.crx.appId = createCrxId(this.crx.keys.publicKey);
                                                           ^

TypeError: Cannot read property 'publicKey' of null
    at CRX3Stream.crxInit (C:\project\temp\lib\crx3stream.js:127:46)
    at CRX3Stream._write (C:\project\temp\lib\crx3stream.js:86:9)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at CRX3Stream.Writable.write (_stream_writable.js:299:11)
    at PassThrough.ondata (_stream_readable.js:693:20)
    at PassThrough.emit (events.js:193:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at PassThrough.Readable.push (_stream_readable.js:224:10)
```

Both situation stops when try to read publicKey from .pem key.   It's something wrong with my .pem file? But, I can generate .crx file if I use Chrome application and then it's will work in Google Chrome. I don't like this method. 
```
chrome.exe --pack-extension=C:/projects/chromeApp/app --pack-extension-key=C:/projects/chromeApp/key.pem 
```
I created this `key.pem` file on Google Chrome 65.xx

**Comment by ahwayakchih** [comment]
I modified code, so it should output error it gets from reading key file.
Can you try it again after pulling those changes?

It's possible that the key type/format is somehow different, but i just used Chromium 77.0.3865.90 to pack example-extension (but through GUI, not CLI) and generate PEM file, and then recreated CRX file using that new PEM key just fine :(.

**Comment by ahwayakchih** [comment]
@BakytzhanAkzhol  I noticed that you're running Node.js 11.6.0. If another run of example fails with something else than file permissions or file non existent error, could you try running it with Node 12.x?

**Comment by BakytzhanAkzhol** [comment]
@ahwayakchih I got your [commit](https://github.com/ahwayakchih/crx3/commit/93ada27dea6d4262ca3ae18e2af932dc72198465) and test it on node.js version 12.5.0. It's worked.

**Comment by ahwayakchih** [comment]
@BakytzhanAkzhol great!

Sorry to bother you, but could you run it on Node v11.6.0 and see what additional error(s) does it show up? I don't have Windows system to test, nor do i have Node v11.6.0 at hand to quickly check it on Linux, so it would be of great help if you could check it and let me know the results :).

**Comment by BakytzhanAkzhol** [comment]
@ahwayakchih Okey. I got new error `CRX_REQUIRD_PROOF_MISSING` when upload generated .crx on Google Chrome -> Extensions(Developer Mode is OFF ). I know why its happen, but it must be solve through your library. .(((

**Comment by BakytzhanAkzhol** [comment]
> @BakytzhanAkzhol great!
> 
> Sorry to bother you, but could you run it on Node v11.6.0 and see what additional error(s) does it show up? I don't have Windows system to test, nor do i have Node v11.6.0 at hand to quickly check it on Linux, so it would be of great help if you could check it and let me know the results :).
Sure. I will gladly do it. I move to Node version 11.6.0 and got error:
```
Could not load key from "C:\another_projects\temp\crx3\example\example-extension.pem" Error: Failed to read public key
    at Object.createPublicKey (internal/crypto/keys.js:305:10)
    at tryLoadKeyPair (C:\another_projects\temp\crx3\lib\keypair.js:71:23)
    at createKeyPair (C:\another_projects\temp\crx3\lib\keypair.js:45:16)
    at CRX3Stream.crxInit (C:\another_projects\temp\crx3\lib\crx3stream.js:126:19)
    at CRX3Stream._write (C:\another_projects\temp\crx3\lib\crx3stream.js:86:9)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at CRX3Stream.Writable.write (_stream_writable.js:299:11)
    at PassThrough.ondata (_stream_readable.js:693:20)
    at PassThrough.emit (events.js:193:15)
"C:\another_projects\temp\crx3\example\example-extension.pem" already exists but could not be loaded.
C:\another_projects\temp\crx3\lib\crx3stream.js:127
                this.crx.appId = createCrxId(this.crx.keys.publicKey);
                                                           ^

TypeError: Cannot read property 'publicKey' of null
    at CRX3Stream.crxInit (C:\another_projects\temp\crx3\lib\crx3stream.js:127:46)
    at CRX3Stream._write (C:\another_projects\temp\crx3\lib\crx3stream.js:86:9)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at CRX3Stream.Writable.write (_stream_writable.js:299:11)
    at PassThrough.ondata (_stream_readable.js:693:20)
    at PassThrough.emit (events.js:193:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at PassThrough.Readable.push (_stream_readable.js:224:10)
```

**Comment by ahwayakchih** [comment]
@BakytzhanAkzhol thanks! I'll bump minimum required version of Node.js to v12 then (v11 is not supported anyway).

`CRX_REQUIRD_PROOF_MISSING` is a separate issue. I explained it in README - there's no way (that i know of) to work around it on Windows. The only way (not for end-users really, more for testers and corporations) that i found is through policies, but Google's documentation for policies (https://www.chromium.org/administrators/policy-list-3#ExtensionSettings) mentions that:

> For Windows instances that are not joined to a Microsoft® Active Directory® domain, forced installation is limited to apps and extensions listed in the Chrome Web Store.

But i don't have Windows with Active Directory domain (or any Windows at all), so i have no way to test that. I tried to add registry keys on appveyor today, but it did not work, so either i did something wrong, or Active Directory is really required and appveyor does not have it.

If you want, you can try to test policy workaround on Windows with puppeteer. Set up environment variable called `CHROME_BIN` with value set to the path to chrome.exe file. Then run `npm install` in CRX3 module directory again (it has to install additional two modules for the test), and then `npm test` after it.
**WARNING:** it will try to add key (`HKLM\Software\Policies\Google\Chrome\ExtensionSettings`) to Windows registry, so be sure to backup existing one first and then remove/restore it afterwards! Or simply run the test in a disposable virtual machine.
Or try that workaround yourself by manually editing registry and setting up local webserver with XML and CRX files (check `crx3/test/writeCRX3File.js` for more info, especially `setPolicy` functions, `testPolicy` variable and `initTestServer` function :).

**Comment by BakytzhanAkzhol** [comment]
@ahwayakchih Okey, thank you for answer. It's so sadly news for me. My Google application working on users which have limited access to Windows registry and system configuration. It's mean i can't add\edit key on Windows Registry. My Google Application working very well on 100+ users right now, but repeat these steps to install the application for each new user. It will drive me crazy.
So, i  have two ways: 
1. Migrate from Google Chrome application to NW.js or Electron.js. 
2. Talking with Google Support about this trouble. 

Have nice day!

**Comment by ahwayakchih** [comment]
@BakytzhanAkzhol you can upload extension to the Google's web store - users should be able to download and install it then. Unless it's non-public extension, in which case moving to NW.js or Electron.js may indeed be the only option :(.

Have a nice day and thanks for very good reports!

**Comment by BakytzhanAkzhol** [comment]
@ahwayakchih  I did some experiments with Node js version. Your library worked on  version 11.7.0 or above.
1. 11.8.0 Succesfull
2. 11.7.0 Succesfull
3. 11.6.0. Failed
4. 11.5.0 Failed
5. 11.4.0 Failed

**Comment by ahwayakchih** [comment]
@BakytzhanAkzhol great! Thanks :).

**Comment by ahwayakchih** [comment]
I changed minimum required version to v12.
