### ISSUE TITLE
Can't run in GitLab CI

### ISSUE THREAD

**Issue by prochac** [ahwayakchih/crx3#7]
**command**
```
docker run --rm -v $(pwd):/my-extension:rw -w /my-extension node:alpine ./build-extension.sh
```
**build-extension.sh**
```
#!/usr/bin/env sh

npm install crx3
PATH=$PATH:$(npm bin) crx3 --key extension-key.pem --crx ./my-extension.crx chrome-extension
rm -rf package.json package-lock.json ./node_modules
```
**error**
```
npm WARN saveError ENOENT: no such file or directory, open '/mall-discount/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/mall-discount/package.json'
npm WARN mall-discount No description
npm WARN mall-discount No repository field.
npm WARN mall-discount No README data
npm WARN mall-discount No license field.

+ crx3@1.1.1
updated 1 package and audited 20 packages in 1.172s
found 0 vulnerabilities

/mall-discount/node_modules/crx3/lib/crx3stream.js:337
                                public_key: keyPair.publicKey.export({
                                                    ^

TypeError: Cannot read property 'publicKey' of null
    at createCRXFileHeader (/mall-discount/node_modules/crx3/lib/crx3stream.js:337:25)
    at CRX3Stream.crxFinish (/mall-discount/node_modules/crx3/lib/crx3stream.js:146:16)
    at CRX3Stream._final (/mall-discount/node_modules/crx3/lib/crx3stream.js:118:8)
    at callFinal (_stream_writable.js:666:10)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

https://docs.docker.com/v17.12/edge/engine/reference/commandline/run/#options
It works with `--tty`, but `--tty` is not a solution for CI ....

**Comment by ahwayakchih** [comment]
Thanks for report!

At the moment, module checks if it was called from TTY. If not, it assumes that ZIP file is piped to it through stdin. I'm not sure yet why it errors on key in such case, and works ok with TTY. I'll try to fix it over the weekend.

**Comment by ahwayakchih** [comment]
@prochac version in master branch should be fixed now. Can you confirm? I will prepare new release after i'm sure it's fixed :).

**Comment by prochac** [comment]
Confirmed. It works now.
https://github.com/prochac/ahwayakchih-crx3-issue-7

**Comment by ahwayakchih** [comment]
Thanks! I'll prepare release by Monday.

**Comment by ahwayakchih** [comment]
v1.1.2 is ready here and on npm.
