### ISSUE TITLE
"Path must be a string" error

### ISSUE THREAD

**Issue by BoD** [ahwayakchih/crx3#8]
Hi!

Trying this tool for the first time.  I have my extension in an `extension` folder and tried `crx3 extension`, this is the error I get:

```
$ crx3 extension
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at scanList (/usr/local/lib/node_modules/crx3/lib/getFilePaths.js:80:19)
    at scanList (/usr/local/lib/node_modules/crx3/lib/getFilePaths.js:83:39)
    at getFilePaths (/usr/local/lib/node_modules/crx3/lib/getFilePaths.js:31:9)
    at writeCRX3File (/usr/local/lib/node_modules/crx3/lib/writeCRX3File.js:58:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/crx3/bin/crx3.js:19:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by ahwayakchih** [comment]
Hi @BoD,

Could you write some more about how you run it and in what environment (node version, operating system, shell, e.g., bash or zsh, etc...)? I tested it in podman container, with module installed globally, and it worked ok :(. Did you try calling crx3 from parent directory or from within the `extension` directory?

**Comment by karlstevens** [comment]
I get a similar error on Slackware64 14.2 (node version 8.16, bash, crx3 installed globally) called as follows:

```
$ crx3 -o my_extension.crx --crxURL https://[myserver]/[path]/my_extension.crx --appVersion 1.0.5 ./my_extension
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1233:7)
    at scanList (/usr/lib/node_modules/crx3/lib/getFilePaths.js:80:19)
    at scanList (/usr/lib/node_modules/crx3/lib/getFilePaths.js:83:39)
    at getFilePaths (/usr/lib/node_modules/crx3/lib/getFilePaths.js:31:9)
    at writeCRX3File (/usr/lib/node_modules/crx3/lib/writeCRX3File.js:58:10)
    at Object.<anonymous> (/usr/lib/node_modules/crx3/bin/crx3.js:19:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

```

**Comment by ahwayakchih** [comment]
@karlstevens thanks for report and more info :). CRX3 module requires Node.js v12+ (it uses some of the new JavaScript syntax, and most importantly easier to use crypto API from Node.js v12).

Could you try running it using latest stable version of Node.js (12.6.1)? I know that v10 is still in active LTS mode, but only until end of April. Node v8 is not even maintained anymore (at least officially: https://nodejs.org/en/about/releases/).

**Comment by karlstevens** [comment]
Ahh, that would do it.   Looks like Slackbuilds hasn't had an update to node in some time.   I used the binaries from nodejs.org and all works fine.

**Comment by ahwayakchih** [comment]
@karlstevens great! Thanks for info :).
