### ISSUE TITLE
ERR_INVALID_OPT_VALUE

### ISSUE THREAD

**Issue by marcelklehr** [ahwayakchih/crx3#9]
I get this error when not specifying an existing key.

```
TypeError [ERR_INVALID_OPT_VALUE]: The value "undefined" is invalid for option "publicKeyEncoding"
    at parseKeyEncoding (internal/crypto/keygen.js:73:11)
    at check (internal/crypto/keygen.js:240:7)
    at Object.generateKeyPairSync (internal/crypto/keygen.js:53:16)
    at createNewKeyPair (/home/runner/work/floccus/floccus/node_modules/crx3/lib/keypair.js:88:22)
    at createKeyPair (/home/runner/work/floccus/floccus/node_modules/crx3/lib/keypair.js:56:9)
    at CRX3Stream.crxInit (/home/runner/work/floccus/floccus/node_modules/crx3/lib/crx3stream.js:126:19)
    at CRX3Stream._write (/home/runner/work/floccus/floccus/node_modules/crx3/lib/crx3stream.js:86:9)
```

**Comment by marcelklehr** [comment]
Oh. I thought I was using node 13, but I think I'm using node 10.

**Comment by ahwayakchih** [comment]
@marcelklehr could you confirm that by running `node --version` command? CRX3 requires Node 12+.

**Comment by marcelklehr** [comment]
Yep, confirmed. I had a typo in my CI config. Now using node 13 everything works fine. Thanks for your support and for this fine library :) :heart:

**Comment by ahwayakchih** [comment]
@marcelklehr thanks :).
